# Generated by Django 4.1.3 on 2022-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='precoParcial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
