# Generated by Django 4.1.3 on 2022-12-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parceiro',
            },
        ),
    ]
