# Generated by Django 4.1.3 on 2022-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=1000)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'carrosel',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5000, unique=True)),
                ('identificador', models.CharField(max_length=5000, unique=True)),
                ('texto', models.CharField(max_length=5000, unique=True)),
                ('data', models.CharField(max_length=1000)),
                ('imagem', models.CharField(max_length=1000)),
                ('tamanho', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=False)),
                ('margin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('imagem', models.CharField(max_length=1000, unique=True)),
                ('tamanho', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sorteio',
            },
        ),
    ]
